contest_9_task_Q
aspasswrd/AlgorithmsAndDataStructures pull request #10
Opened 2024-05-19 18:58 UTC by aspasswrd

2024-05-20 19:58 UTC, Polinakleidman requested changes

2024-05-20 19:58 UTC, Polinakleidman commented on contest_9/contest_9_task_Q.cpp
> +struct Flow {
class

2024-05-20 19:58 UTC, Polinakleidman commented on contest_9/contest_9_task_Q.cpp
> +  explicit Flow(ll n) : n(n) {
инициализацию векторов тоже лучше в списке инициализации

2024-05-20 19:58 UTC, Polinakleidman commented on contest_9/contest_9_task_Q.cpp
> +  const ll cInf = 1e18;
private

2024-05-20 19:58 UTC, Polinakleidman commented on contest_9/contest_9_task_Q.cpp
> +  ll v;
непонятные нейминги

2024-05-21 15:32 UTC, aspasswrd commented on contest_9/contest_9_task_Q.cpp
> +  explicit Flow(ll n) : n(n) {
а как... Я же их просто ресайзаю

2024-05-21 15:52 UTC, aspasswrd commented on contest_9/contest_9_task_Q.cpp
> +  explicit Flow(ll n) : n(n) {
нашёл ответ в ревью к другой задаче)

2024-05-21 20:15 UTC, merged